# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Goodnight Loving
email: colinjswinney@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A website built half a decade too late for a long broken up band.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://colinswinney.github.io" # the base hostname & protocol for your site
twitter_username: ColinJSwinney
github_username:  colinswinney
permalink: :categories/:title
nickname: G.N.L.
excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
